export * from "./Blog"
export * from "./English"
export * from "./Home"
export * from "./Icons"
export * from "./InfoPage"
export * from "./NotFound"
export * from "./Search"
export * from "./Statistic"